config/routes.rb
Rails.application.routes.draw do

  get "cocktail/elm"
  get "cocktail/halogen"
  get "cocktail/flame"

  get "elm_form/new"
  get "elm_form/index"
  post "elm_form/index"

  get "pure_script/show_halogen"
  get "pure_script/show_flame"
  get "re_script/show"

  post "api/read-file" => "api/files#read"
  post "api/list-files" => "api/files#list"
  #  second example for clarity
  get  "api/get-files"  => "api/files#get"

  get "home/page"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/elm_form.rb
class ElmForm
  include ActiveModel::Model

  attr_accessor :fexid, :compid, :brid


  # ContactMessage are never persisted in the DB
  def persisted?
    false
  end

  def elm_forms_path
    '/zzz'
  end
end

app/models/concerns/files.rb
class Files
  def initialize(pwd, show_hidden)
    @dir = Dir.open pwd
    @show_hidden = show_hidden
    @files = @dir
               .entries
               .sort
               .map { |f|
      begin
        File.new(File.join(@dir.path, f))
      rescue
        [ f, $! ]
      end
    }
               .map { |f|
      if f.is_a?(File)
        { name: File.basename(f),
          executable: File.executable?(f),
          extname: File.extname(f),
          ftype: File.ftype(f),
          size: File.size(f),
          mtime: File.stat(f).mtime,
          mode: File.stat(f).mode,
          symlink: File.stat(f).symlink?
        }
      else # dodgy second variant
        { name: f.first,
          executable: false,
          extname: "",
          ftype: f.second,
          size: 0,
          mtime: "",
          mode: 0,
          symlink: false
        }
      end
    }
  end

  # puts Files.new('/home/jacek/', false).data.to_json
  def data
    { pwd: @dir.to_path,
      show_hidden: @show_hidden,
      files:
        if @show_hidden
          @files
        else
          @files.reject { |f|  f[:name].start_with?(".") }
        end
    }
  end
end

app/controllers/api/files_controller.rb
class Api::FilesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def read
    render plain: File.open(File.join(params['pwd'], params['fname'])).read
  end

  def list
    params.permit!

    render json: Files.new(params["pwd"], params["show_hidden"]).data
  end

  def get
    params.permit!

    logger.info "doing get for params #{params.inspect}"

    dir = Dir.open(params["pwd"])

    files = dir.entries.sort
    files_filtered =
      if params["show_hidden"]
        files
      else
        files.reject { |f| f.start_with?(".") }
      end

    render json: { pwd: dir.to_path,
                   show_hidden: params["show_hidden"],
                   files: files_filtered }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/cocktail_controller.rb
class CocktailController < ApplicationController
  def elm
  end

  def halogen
  end

  def flame
  end
end

app/controllers/elm_form_controller.rb
class ElmFormController < ApplicationController
  def index
  end

  def new
    @elm_form = ElmForm.new
    @elm_form.fexid = 1
    @elm_form.compid = 2
    @elm_form.brid = 3
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/pure_script_controller.rb
class PureScriptController < ApplicationController
  def show
  end

  def show_halogen
  end

  def show_flame
  end
end

app/controllers/re_script_controller.rb
class ReScriptController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_helper.rb
module CocktailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pure_script_helper.rb
module PureScriptHelper
end

app/views/cocktail/elm.html.erb
<div id="elm">Please wait...</div>
<%
js_filename = 'elm-cocktails.js'
js_file = File.join(Rails.root, 'public', js_filename)
js_mtime =File.mtime(js_file).to_i

flag_data = {base_url: request.base_url,
             logname:  ENV['LOGNAME']}
%>
<script src=/<%= "#{js_filename}?#{js_mtime}" %>></script>
<script>
 var app = Elm.Cocktails.init({ node: document.getElementById('elm'),
                                flags: <%= raw JSON.generate flag_data %>
 })
 // you can use ports and stuff here
</script>

app/views/cocktail/flame.html.erb
<h1>Struggling with Purescript</h1>

<p>After lack of progress with Halogen, I am trying Elm
</p>

<div id="flame-cocktail"></div>

<%
js_filename = 'flame-cocktail.js'
js_file = File.join(Rails.root, 'public', js_filename)
# prepare my own fingerprinting
js_mtime =File.mtime(js_file).to_i

html_attributes = {type: 'module', id: 'flame-cocktail-flags'}
flag_data = {
  base_url: request.base_url,
  logname:  ENV['LOGNAME'],
  start: 7
}.each{ |k,v| html_attributes[:"data-#{k}"] = v }
%>

<%= javascript_include_tag "/#{js_filename}?#{js_mtime}", html_attributes %>

app/views/cocktail/halogen.html.erb
<h1>Struggling with Purescript</h1>

<p>After initial struggle, I got to the point where I can crate basic elements of the page.
</p>

<div id="halogen-cocktail"></div>

<%
js_filename = 'halogen-cocktail.js'
js_file = File.join(Rails.root, 'public', js_filename)
# prepare my own fingerprinting
js_mtime =File.mtime(js_file).to_i

html_attributes = {type: 'module', id: 'halogen-cocktail-flags'}
flag_data = {
  base_url: request.base_url,
  logname:  ENV['LOGNAME'],
  start: 7
}.each{ |k,v| html_attributes[:"data-#{k}"] = v }
%>

<%= javascript_include_tag "/#{js_filename}?#{js_mtime}", html_attributes %>

app/views/elm_form/index.html.erb
elm for index

<p>
  params
  <%= params.inspect  %>
</p>

app/views/elm_form/new.html.erb
elm for new


<%= form_tag(elm_form_index_path, method: :post) do -%>
  <div id="elm"></div>

  <!--
       <%= label_tag 'fexid' %>
       <%= text_field_tag 'fexid' %>
       <br>
       <%= label_tag 'compid' %>
       <%= text_field_tag 'compid' %>
       <br>
       <%= label_tag 'brid' %>
       <%= text_field_tag 'brid' %>
       <br>
  -->
  <%= submit_tag "Submit"  %>
<% end %>

<%
js_filename = 'elm_form_new.js'
js_file = File.join(Rails.root, 'public', js_filename)
js_mtime =File.mtime(js_file).to_i

flag_data = {base_url: request.base_url}
%>
<script src="<%= "/#{js_filename}?#{js_mtime}" %>"></script>
<script>
 var app = Elm.ElmFormNew.init({ node: document.getElementById('elm'),
                                 flags: <%= raw JSON.generate flag_data %>
 })
 // you can use ports and stuff here
</script>

app/views/home/halogen.html.erb
%h1 Halogen Cocktail

app/views/home/page.html.erb
<h1>Home#page</h1>
<p>Find me in app/views/home/page.html.erb</p>
<h1>Elm-UI links</h1>
<p style="background: yellow; padding:1em">
  <a href="https://korban.net/elm/elm-ui-patterns/" target="_blank">Elm-UI patterns </a>
</p>

<div id="elm"></div>
<%
js_filename = 'ui-experiment.js'
js_file = File.join(Rails.root, 'public', js_filename)
js_mtime =File.mtime(js_file).to_i

flag_data = {base_url: request.base_url,
             logname:  ENV['LOGNAME'],
             home:  ENV['HOME'],
             showHidden: false}
%>
<script src="<%= "#{js_filename}?#{js_mtime}" %>"></script>
<script>
 var app = Elm.UiExperiment.init({ node: document.getElementById('elm'),
                                   flags: <%= raw JSON.generate flag_data %>
 })
 // you can use ports and stuff here
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Trying Elm Ui" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <% # = javascript_importmap_tags %>

    <style>
     .dropbtn {
       background-color: #3498DB;
       color: white;
       padding: 16px;
       font-size: 16px;
       border: none;
       cursor: pointer;
     }

     .dropbtn:hover, .dropbtn:focus {
       background-color: #2980B9;
     }

     .dropdown {
       position: absolute;
       display: inline-block;
     }

     .dropdown-content {
       display: none;
       position: absolute;
       background-color: #f1f1f1;
       max-width: 250px;
       width: max-content;
       max-height:300px;
       overflow: auto;
       box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
       z-index: 1;
     }

     .dropdown-content a {
       color: black;
       padding: 5px 16px;
       text-decoration: none;
       display: block;
     }

     .dropdown a:hover {background-color: #ddd;}
     .dropdown span:hover {background-color: #ddd;}

     .show {display: block;}
    </style>
  </head>
  <body>
    <div>

      <%= link_to 'Home Elm', '/', data: {turbo: false} %>
      |
      <%= link_to 'Purescript Halogen', pure_script_show_halogen_path, data: {turbo: false} %>
      |
      <%= link_to 'Purescript Flame', pure_script_show_flame_path, data: {turbo: false} %>
      |
      <%= link_to 'Rescript 1', re_script_show_path, data: {turbo: false} %>
      |
      <%= link_to 'Form new', elm_form_new_path, data: {turbo: false} %>
      |
      <%= link_to 'Form index', elm_form_index_path, data: {turbo: false} %>

      |
      <%= link_to 'Elm Cocktails', cocktail_elm_path, data: {turbo: false} %>
      |
      <%= link_to 'Halogen Cocktails', cocktail_halogen_path , data: {turbo: false} %>
      |
      <%= link_to 'Flame Cocktails', cocktail_flame_path , data: {turbo: false} %>



    </div>

    <%= yield %>
  </body>
</html>

app/views/pure_script/show.html.erb
<h1>PureScript#show</h1>
<p>Find me in app/views/pure_script/show.html.erb</p>

<p>
  We need to link the index.js file from the PureScript app to the public folder of the Rails app
</p>

<pre>
  cd ~/Programming/Rails/trying-elm-ui/public/
  rm ./index.js
  ln -s /home/jacek/Programming/Pyrulis/Purescript/halogen/counter/prod/index.js ./index.js
</pre>


<%
js_filename = 'index.js'
js_file = File.join(Rails.root, 'public', js_filename)
# prepare my own fingerprinting
js_mtime =File.mtime(js_file).to_i
%>

<%= javascript_include_tag "/#{js_filename}?#{js_mtime}", type: 'module' %>

app/views/pure_script/show_flame.html.erb
<h1>PureScript#show</h1>
<p>Find me in app/views/pure_script/show_flame.html.erb</p>


<!-- flame will show the output in this div -->
<div id="flame" style="border: solid blue 1px"></div>

<footer style="background: yellow">Footer</footer>

<%
js_filename = 'index_flame.js'
js_file = File.join(Rails.root, 'public', js_filename)
# prepare my own fingerprinting
js_mtime =File.mtime(js_file).to_i

flags = {
  'counter-start' => '12',
  'base-url' =>    request.base_url,
  'logname' =>     ENV['LOGNAME'],
  'home'  =>       ENV['HOME'],
  'show-hidden' => false
        }
%>

<%= javascript_include_tag "/#{js_filename}?#{js_mtime}", type: 'module', id: 'flame_flags', data: flags  %>

app/views/pure_script/show_halogen.html.erb
<h1>PureScript#show</h1>
<p>Find me in app/views/pure_script/show_halogen.html.erb</p>

<p>
  We need to link the index.js file from the PureScript app to the public folder of the Rails app
</p>

<pre>
  cd ~/Programming/Rails/trying-elm-ui/public/

  cp -v /home/jacek/Programming/Pyrulis/Purescript/halogen/counter/prod/index.js ./index_halogen.js
</pre>


<div id="halogen"></div>

<footer>Footer</footer>

<%
js_filename = 'index_halogen.js'
js_file = File.join(Rails.root, 'public', js_filename)
# prepare my own fingerprinting
js_mtime =File.mtime(js_file).to_i
%>

<%= javascript_include_tag "/#{js_filename}?#{js_mtime}", type: 'module', id: 'script_with_flags', :'data-my-app--api-endpoint'=> "https://example.com/", :'data-my-app--api-key' => '123456', :'data-my-app--count-start' => 7 %>

app/views/re_script/show.html.erb
<% content_for :head do %>
  <!-- head comment -->
  <link rel="stylesheet" href="/index_rescript.css" data-turbo-track="reload">
<% end %>

<!--  file:~/Programming/Rails/trying-elm-ui/vendor/rescript/my-rectript-experiment/dist/index.html::1 -->
<!DOCTYPE html>
<!-- <html lang="en">

     <head>
     <meta charset="UTF-8" />
     <link rel="icon" type="image/svg+xml" href="/vite.svg" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <title>ReScript + Vite + React</title>
     <link href="/dist/styles.css" rel="stylesheet">
     <script type="module" crossorigin src="/assets/index-CGiRQrRV.js"></script>
     <link rel="stylesheet" crossorigin href="/assets/index-D0AoTKhA.css">
     </head>
-->
<h1>First Rescript</h1>

<div id="root" class="h-screen flex justify-center items-center"></div>

<script type="module" crossorigin src="/index_rescript.js"></script>